apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
  labels:
    app: reactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: REPOSITORY_TAG

---

apiVersion: v1
kind: Service
metadata:
  name: reactapp-svc
spec:
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 5173

