name: build & publish docker image
on: workflow_dispatch

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      
      - name: Code Checkout
        uses: actions/checkout@v4.1.5

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}

      - name: Build Image
        run: | 
          docker build -t reactimg:v1 .
          docker tag reactimg:v1 frankisinfotech/demo-react:v1
          docker push frankisinfotech/demo-react:v1

    
